### PR TITLE
Venator pivot

### PR DESCRIPTION
**Pull request by izar**
Hi there, just a quick hack to run VirusTotal queries on hashes straight from Venator.

### CODE REVIEW

**Comment by richiercyrus** [comment]
Thanks for this. Initially, it looks great! Gonna do some testing this weekend before merging.

**Comment by izar** [comment]
bump

**Comment by richiercyrus** [comment]
Thanks for your contribution. The part of the code that makes the VirusTotal requests needs additional work before I can push to master. Added my key as ENV variable however, only three requests happen. I will attempt to work on fixing it however, my main priority for this project at this moment is porting it to Swift. If you get the VT part working before I can, I'd be happy to add it.

**Comment by richiercyrus** [comment]
I think I am close to finishing the VT code tweaks. Should be merged into master sometime this week.

**Pull request merged**
